# Site settings
title: pkill.io - I have my thoughts. Here are some of them.
email: pkill@linux.com
fullname: "Alex Elman"
jobtitle: "Linux Systems Engineer"
description: > # this means to ignore newlines until "baseurl:"
  I contribute to FOSS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pkill.io" # the base hostname & protocol for your site
twitter_username: _pkill
github_username:  pkill

# Build settings
highlighter: pygments
markdown: kramdown
