url: "https://pkill.io" # the base hostname & protocol for your site.
title: "pkill.io - Emphatic drivel and shocking nonesense"
email: pkill@linux.com
safeemail: "pkill (at) linux.com"
fullname: "Alex Elman"
jobtitle: "Site Reliability Engineer"
physical_location: "Austin, TX"
description: > # this means to ignore newlines until "baseurl:"
  Notes on Linux, open source, journalism, security & privacy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pkill.io" # the base hostname & protocol for your site
twitter_username: _pkill
github_username:  pkill
freenode_username: _pkill

# Build settings
highlighter: pygments
markdown: kramdown

paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/pkill"
stackoverflow: "http://stackoverflow.com/users/974060/pkill"
twitter: "https://twitter.com/_pkill"
linkedin: "https://linkedin.com/in/pkill"
#disqus comment
disqus:
    shortname: "pkill"

#google analytics
google:
    tracking-id: "UA-59435864-1"
gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
